- .pre-commit-config.yaml
It turns out that -L lets you provide a list of words to ignore on the command line. What we actually want is to provide a file with a list of words to be ignored. The correct option for this is -I.
See: https://github.com/ImperialCollegeLondon/python-template/pull/137
> Fix codespell hook

- imperial_coldfront_plugin/models.py
- Introduces a new `GroupMember` model to provide a direct representation of research groups.
- Adds `owner` and `member` fields as ForeignKey references to the user model, designating a group owner and associated member.
- This initial implementation lays the groundwork for expanding research group functionality in future updates.
Notes to reviewers:
- Please verify that the `on_delete` behaviour is appropriate for the use case.
- Migrations are not yet included, as `django manage.py` is currently unavailable.
Fixes #17
> Add Django GroupMember model to represent research groups directly.

- README.md
- makemigrations.py
- pyproject.toml
This pull request includes the addition of a new script and corresponding documentation to facilitate making migrations in a standalone Django application. The most important changes include adding a helper script for generating migrations and updating the README file with instructions on how to use this script.
Fixes #25
> Support making migrations

- .github/dependabot.yml
- .github/workflows/upgrade-dependencies.yml
This PR implements a custom action to upgrade the dependencies and open a PR using `pip-compile` directly instead of dependabot's `pip` option. This respects the restrictions in `pyproject.toml` and ensure the secondary dependencies are consistent with the primary ones.
I tested this by running it on `push`, which can be seen in , and resulted in PR #44 
Limitations:
- The CI workflows do not run in the resultant PR, to fix this we should use the RSE CI bot (see [these docs](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs))
- If we want these to auto-merge, we will need to add the appropriate PR user to the `auto-merge.yml` workflow
Fixes #29
> Dependency upgrade action

- dev-requirements.txt
- doc-requirements.txt
- imperial_coldfront_plugin/oidc.py
- pyproject.toml
- requirements.txt
The original plan was to get uid values from LDAP but after discussion with the identity team they were able to add the uid data to the user data stored in Azure. That means we can now retrieve uid values from the Microsoft Entra Graph API user the access token from the login workflow. This has a number advantages over the previous LDAP implementation:
- simplicity (compare this PR with #42)
- no extra dependencies
- uses only 1 source for all identity data
- no additional settings
To test this:
- Clear the development database (`docker compose down -v`).
- Make sure the main branch of the development environment is up to date.
- Make sure you have the OIDC environment variables set.
- Start the server and login via the browser and Imperial SSO.
- Open a shell `docker compose exec app …
> Get user uids from Microsoft Graph API

- imperial_coldfront_plugin/templates/no_group.html
- tests/test_views.py
Fixes #47 
The bug was already fixed so this PR just removes the xfails that were left over. I was under the impression that pytest would flag an xfail marked test if it did not fail.
> Remove xfails

- imperial_coldfront_plugin/utils.py
- imperial_coldfront_plugin/views.py
- tests/conftest.py
- tests/test_views.py
Implements a wrapper function to make it simple to send emails as a background task and refactors the one view that sends emails already.
I've added a configuration for Django Q to the development environment so make sure you've got the latest `main` if you want to run it locally.
Fixes #89
> Send emails in background

- imperial_coldfront_plugin/microsoft_graph_client.py
- imperial_coldfront_plugin/policy.py
- imperial_coldfront_plugin/views.py
- tests/conftest.py
- tests/test_microsoft_graph_client.py
- tests/test_policy.py
- tests/test_views.py
Fixes #103 
As described by the issue, current searches of the microsoft graph api return entities that should not be considered for HPC access e.g. rooms. This PR implements some basic filtering using the profile data returned from the API to catch obviously invalid entries.
> Filter entities returned graph api based on user profile

- imperial_coldfront_plugin/templates/group_members.html
- imperial_coldfront_plugin/urls.py
- imperial_coldfront_plugin/views.py
- tests/test_views.py
Added two view functions for adding and removing users, respectively. 
I have added a link as the HTML page doesn't look the cleanest, so can change if needed. 
Fixes #73 #93 (issue)
> Group managers UI

- imperial_coldfront_plugin/urls.py
- imperial_coldfront_plugin/views.py
- tests/test_views.py
This adds a view to provide the /etc/groups endpoint for SoV
One thing I noticed when doing this is that there are no restriction on the ResearchGroup name. It needs to have the same restrictions as a unix group name (ie no spaces, possibly more). Should this be a new issue?
Fixes #36
> Implement get_group_data view

- imperial_coldfront_plugin/policy.py
- tests/test_policy.py
A port of the PI identification logic from the old portal. At the moment this is a single function in the policy module (and tests) that will be used in later PRs.
Fixes #65
> Automatic PI identification

- imperial_coldfront_plugin/forms.py
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/extend_membership.html
- imperial_coldfront_plugin/urls.py
- imperial_coldfront_plugin/views.py
- tests/test_views.py
This PR adds a new group membership extension view function using the group membership pk as an argument.
To do:
Fixes #86
> Add group membership extension view function

- imperial_coldfront_plugin/urls.py
- imperial_coldfront_plugin/views.py
- tests/conftest.py
- tests/test_views.py
This just changes the view function to take the group ID as an argument for the group members view function. 
As a result of this change some other view functions that redirect to the members view had to be changed so did the tests. =
One thing broken is the navbar link which i will fix later on in #117 . 
Fixes #107  (issue)
> modifying the group memebers view function

- imperial_coldfront_plugin/forms.py
- imperial_coldfront_plugin/views.py
- tests/test_views.py
Adds a group membership expiration field to the invite form, and use it in the send and accept invite views.
NB: neither datetimes nor timedeltas may be serialised by the token fn, so I instead used an ISO format datetime string. Not really sure how to feed in py datetimes from `user_search.html` though, so haven't done that.
Test added to check that membership expiry is not in past.
Fixes #90
> Grp expire send accept

- imperial_coldfront_plugin/forms.py
- imperial_coldfront_plugin/templates/group_members.html
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/user_search.html
- imperial_coldfront_plugin/views.py
- tests/test_views.py
Read a chosen membership expiration from the user_search.html invite form. Also display expiration in the group view.
Change the form to use a date, not a datetime -- seems silly to chose the minute of expiration.
Some light JS was necessary to enforce minimum today's date, and maximum some way into the future: currently 5 years. Can maybe be a setting passed into the template?
Fix a double quite typo: `<form action="{% url 'imperial_coldfront_plugin:send_group_invite' %}" method="post"">`.
Fixes #84
> UI changes for group membership expiration

- imperial_coldfront_plugin/policy.py
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/eligible_pi.html
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/home.html
- imperial_coldfront_plugin/templatetags/__init__.py
- imperial_coldfront_plugin/templatetags/home_tags.py
- tests/conftest.py
- tests/test_policy.py
- tests/test_templatetags.py
- tests/test_views.py
Overrides the template for the base Coldfront home view to customise it with our content. I was hoping this could be carried out only in the plugin but have had to also implement an override in the development override so please make sure you have the `home-override` branch checked out in the development environment when testing this.
As we are only updating a template and not the view function we're not able to control the context that is passed to the template. To work around this we use template tags which effectively allow calling custom python code during template rending.
The tests also have to check the template rendering directly rather than calling the view function as it is tricky to call one of the coldfront views in the plugin tests.
Does not yet include a link to create the …
> Override coldfront home page

- imperial_coldfront_plugin/emails.py
- imperial_coldfront_plugin/templates/group_members.html
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/accept_group_invite.html
- imperial_coldfront_plugin/views.py
- tests/test_views.py
This pull request addresses the following:
- Adds a membership extension section to the group members page
- Updates the group invitation acceptance message to include expiration details, and modifies the corresponding view to pass the expiration context.
Fixes #87, #123
> Group membership extension UI + expiry info add

- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/group_menu.html
- imperial_coldfront_plugin/templatetags/navbar_tags.py
- tests/test_templatetags.py
This was broken by #118. Adds a template tag that checks if a user is the owner or manager of a group and if so returns the url to view it. This tag is used by the template to populate the "Manage your group" item in the navbar.
Fixes #117
> Fix "manage your group" menu item

- imperial_coldfront_plugin/views.py
- tests/conftest.py
- tests/test_templatetags.py
- tests/test_views.py
This PR:
- takes a pass at the testing fixtures used for different roles and provides parametrised fixtures to run tests multiple times with different user roles.
- standarises and corrects the permissions applied to certain view functions and updates the tests to reflect these.
- introduces a new testing mixin for view functions that take a GroupMembership primary key as an argument.
These changes lay the groundwork for #140 and #131.
> Testing Refactor

- imperial_coldfront_plugin/policy.py
- imperial_coldfront_plugin/views.py
- tests/test_policy.py
- tests/test_views.py
This PR captures the common logic relating to permissions for different view functions. It also adds a check that a group managers membership has not expired.
Fixes #140
> Standardise view permission checks

- imperial_coldfront_plugin/policy.py
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/user_search.html
- imperial_coldfront_plugin/views.py
- tests/test_policy.py
- tests/test_views.py
If a user is already a member of a group then this PR means that they no longer appear in search results when adding new group members and prevents a new invitation being sent to them. This primarily a QoL change as the database schema already prevents them being added to another group.
Fixes #134
> Account for existing group members when adding new group members

- imperial_coldfront_plugin/microsoft_graph_client.py
Updates the `_transform_profile_data` function to prevent unhandled exceptions in the case of missing user profile data.
Fixes # (issue)
> Bug fix in case of being unable to access user profile data

- imperial_coldfront_plugin/templates/group_members.html
- imperial_coldfront_plugin/views.py
- tests/test_views.py
This pull request includes changes to handle that expired group memberships cannot be made managers.
Fixes #125
> Expired member cannot be made manager

- imperial_coldfront_plugin/gpfs_client.py
This pull request adding methods to set quotas on filesystems. The changes include the addition of a private method `_set_quota` and a public method `set_quota`.
Fixes #182
> GPFS client: set quotas

- imperial_coldfront_plugin/apps.py
- imperial_coldfront_plugin/ldap.py
- imperial_coldfront_plugin/signals.py
- tests/conftest.py
- tests/test_ldap.py
- tests/test_signals.py
- tests/test_views.py
This PR adds the logic to syncronise the assigned of users to allocations within Coldfront with membership of the relevant group in active directory. It provides:
- ldap utility functionality to get a users [DN](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/distinguished-names) (distinguished name) from their imperial username.
- ldap functions to add/remove members to/from a group.
- a pair of signals that handle syncing changes in the Coldfront database with the LDAP server.
Similarly to #177 there is unfortunately no way to try this out locally at the moment.
Fixes #167 #168
> Add/Remove members from AD groups

- imperial_coldfront_plugin/forms.py
- imperial_coldfront_plugin/migrations/0010_auto_20250228_1431.py
- imperial_coldfront_plugin/views.py
- tests/test_views.py
This pull request adds a `dart_id` field to the `RDFAllocationForm` class which is not  editable by end users.
Fixes #196
> Add DART id to `RDFAllocation`

- imperial_coldfront_plugin/ldap.py
- imperial_coldfront_plugin/migrations/0010_auto_20250228_1431.py
- imperial_coldfront_plugin/views.py
- tests/conftest.py
For simplicity and consistency this PR renames the RDF storage resource type from "RDF Project Storage Space" to "RDF Active". This should be clearer to users as "RDF Active" is the name of the actual service they're consuming. Note this is a bit naughty to modify the existing data migration. You'll need to wipe the existing database (`docker compose down -v`) to get a consistent state after this PR is merged.
> Rename RDF resource to "RDF Active"

- imperial_coldfront_plugin/dart.py
- imperial_coldfront_plugin/forms.py
- imperial_coldfront_plugin/migrations/0010_auto_20250228_1431.py
- imperial_coldfront_plugin/policy.py
- imperial_coldfront_plugin/templates/imperial_coldfront_plugin/dart_id_form.html
- imperial_coldfront_plugin/urls.py
- imperial_coldfront_plugin/views.py
- tests/test_forms.py
- tests/test_views.py
Validates and prevents duplicates of Dart ID values set as AllocationAttributes. Also provides a dedicated route for users/superusers to add additional Dart ID's to an allocation. Also updates the `DART ID` AllocationAttributeType to not be private.
Fixes # (issue)
> More sophisticated treatment of Dart ID's
